# -*- coding: utf-8 -*-
"""
Created on Wed Feb 24 11:22:26 2021

@author: Valentin Laplaud

Useful generic functions 

"""


import numpy 
import pandas as pd

import matplotlib.pyplot as plt
import seaborn

#  1. Loading text files from IJ

# A general function created to read txt files generated by imageJ, 
# and return a dataframe with the desired columns


def LoadImageJResults(FilePath,Columns):
   
        F = open(FilePath,'r') # Open file for reading
        lines = F.readlines() # Read all lines of the file

        Data = pd.DataFrame(data=None)
        
        for c in Columns:
            
            # find the column number in the text file header
            nC = lines[0].rstrip('\n').split('\t').index(c) 

            data = [] # temp data storage
        
            for l in lines[1:]:
                data = numpy.append(data,numpy.float(l.rstrip('\n').split('\t')[nC]))  
                # adds data from the file line by line
                # also removes '\n' from the last columns if present

            Data[c] = data # adding columns to dataframe
        
        return(Data) # return dataframe
    
#  2. Plotting boxplots with data points on top (from panda dataframe)

# A function combining panda.dataframe.plot with seaborn's swarmplot for a better display of data

def df2boxswarm(Data,columns,**kwargs):

    Title = None
    
    for key, value in kwargs.items(): 
        if key == 'suptitle':
            Title = value
        else:            
            print('Unknown key : ' + key+ '. Kwarg ignored.')
    
    Ld = len(Data)
    Lc = len(columns)
    
    xGrouping = numpy.concatenate(([0],numpy.concatenate(([numpy.ones(Ld)*x for x in range(1,Lc+1)]))))
    
    
    seaborn.swarmplot(x=xGrouping,
                      y=numpy.concatenate(([10],numpy.concatenate(([Data[c].to_numpy() for c in columns])))))  
    plt.xticks(ticks = list(range(1,Lc+1)), labels = columns)
    Data.boxplot(columns)                                    
    
    plt.xlim(0.5,Lc+0.5)
    fig = plt.gcf()
    fig.set_dpi(150)
    fig.suptitle(Title)

# 3. Coordinate conversion from cartesian to circular (in deg) an vice versa

def ToCirc(X,Y, **kwargs):
    
    Angle = 'rad'
    
    for key, value in kwargs.items(): 
        if key == 'angle':
            Angle = value
        else:            
            print('Unknown key : ' + key+ '. Kwarg ignored.')
    
    
    if Angle == 'deg':
        Alpha = numpy.rad2deg(numpy.arctan2(Y,X))
    elif Angle == 'rad':
        Alpha = numpy.arctan2(Y,X)
    else:
        print('Wrong angle unit : ' + Angle + '. Default to radians.')         
        Alpha = numpy.arctan2(Y,X)
        
    Radius = numpy.sqrt(numpy.square(X)+numpy.square(Y))
    
    return(Alpha,Radius)



def ToCart(Alpha,Radius, **kwargs):
    
    Angle = 'rad'
    
    for key, value in kwargs.items(): 
        if key == 'angle':
            Angle = value
        else:            
            print('Unknown key : ' + key + '. Kwarg ignored.')
    
    if Angle == 'deg':
        Alpharad = numpy.deg2rad(Alpha)
    elif Angle == 'rad':
        Alpharad = Alpha
    else:
        print('Wrong angle unit : ' + Angle + '. Default to radians.') 
        Alpharad = Alpha
    
    
    X = Radius*numpy.cos(Alpharad)
    Y = Radius*numpy.sin(Alpharad)
    
    return(X,Y)
    
